### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by almarklein** [plotly/dash-slicer#1]
To keep track of progress:

* [x] id's defined must be made unique so one can use multiple slicers in one app.
* [x] Figure out how to "connect" multiple views on the same data. #4
* [x] Add indicators for other slices. #4
* [x] Use image traces, see https://github.com/plotly/dash-3d-viewer/pull/2#discussion_r514254961 #3
* [x] Support anisotropic data and flipping axis'. #8
* [x] callbacks are now defined before the layout, which is not supposed to work? -> I read it the wrong way.
* [x] Make it possible to show low-res data as a placeholder. #3
* [x] Look into that React error  / warning. -> It seems to be gone :)
* [x] Different behavior for slider drag and slider release:
  * Rate limiting is implemented in #24
  * https://github.com/plotly/dash-core-components/pull/884
* [x] Release
* [x] Docs
* [x] Allow indicators to be different colors? #29
* [x] API to show extra traces in the figure. #40 
* [x] Support for setting contrast limits. #47
* [x] Make it configurable what data is uploaded at the start (none, low-res, full-res). #34
* [ ] Colormaps. #49

Ideas maybe worth considering:
* More ways to control the slice index -> #11
* Define slice using a plane instead of an axis + index (needs interpolation with e.g. numba). -> probably out of scope - if going this way, keep the views orthogonal.
